[package]
name = "stretchable"
version = "1.0.0-a1"
edition = "2021"
authors = ["Kenneth Trelborg Vestergaard"]
description = "Python bindings for Stretch (high performance flexbox implementation)"

[lib]
name = "stretchable"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.6", features = ["abi3-py37", "extension-module"] }
dict_derive = "0.4.0"
stretch = "0.3.2"
